name: feelmeweb
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  cupertino_icons: ^1.0.8
  intl: 0.19.0
  http: ^1.2.0

  base_class_gen:
    path: base_class_gen
  provider: 6.0.5
  injectable: 2.3.2
  google_maps_flutter_web: ^0.5.10
  google_maps_flutter: ^2.10.0
  get_it: 7.6.4
  http_parser: ^4.0.2
  page_transition: 2.0.9
  permission_handler: ^11.3.1
  location: ^7.0.1
  shared_preferences: 2.2.2
  flutter_secure_storage: 9.0.0
  flutter_svg: 2.0.7
  connectivity_plus: 5.0.1
  mask_text_input_formatter: 2.5.0
  uuid: ^4.2.2
  easy_localization: 3.0.7
  google_fonts: 5.1.0
  frontend_server_client: ^4.0.0
  go_router: ^14.3.0
  json_annotation: 4.8.1
  collection: ^1.18.0

dev_dependencies:
  injectable_generator: 2.4.1
  build_runner: 2.4.13
  json_serializable: 6.7.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
